export SNPSLMD_LICENSE_FILE=27000@192.168.0.111
export SYNOPSYS_ROOT=/home/tools/synopsys
CUSTOM_COMPILER=${SYNOPSYS_ROOT}/customcompiler/O-2018.09-SP1-3
CUSTOM_WAVEVIEW=${SYNOPSYS_ROOT}/wv/O-2018.09-SP2
ICV_HOME_DIR=${SYNOPSYS_ROOT}/icvalidator/O-2018.06-SP2-6
STARRC_ROOT=${SYNOPSYS_ROOT}/starrc/N-2017.12-SP3-4
HSPICE_ROOT=${SYNOPSYS_ROOT}/hspice/O-2018.09-SP2/hspice
#HSIM_PLUS=${SYNOPSYS_ROOT}/hsim/N-2017.12-SP2/hsimplus
FINESIM=${SYNOPSYS_ROOT}/finesim/O-2018.09-SP2-1
CUSTOM_SIM=${SYNOPSYS_ROOT}/xa/O-2018.09-SP4
export VCS_TARGET_ARCH="linux64"
export VCS_HOME=${SYNOPSYS_ROOT}/vcs-mx/O-2018.09-SP2-11/
export VERDI_HOME=${SYNOPSYS_ROOT}/verdi/Verdi_N-2017.12/
export PATH=${CUSTOM_COMPILER}/bin:$PATH
export PATH=${CUSTOM_WAVEVIEW}/bin:$PATH
export PATH=${ICV_HOME_DIR}/bin:$PATH
export PATH=${STARRC_ROOT}/bin:$PATH
export PATH=${HSPICE_ROOT}/bin:$PATH
export PATH=${HSIM_PLUS}/bin:$PATH
export PATH=${FINESIM}/bin:$PATH
export PATH=${CUSTOM_SIM}/bin:$PATH
export PATH=${VCS_HOME}/bin:$PATH
export PATH=${VERDI_HOME}/bin:$PATH
export ADC_PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export TSMC_LIB=/home/dkits/tsmc_65/65MSRFGP_PDK/pdk_rf_1p9m_6X1Z1U/tsmcN65
export SNPS_LIB=/home/tools/synopsys/customcompiler/O-2018.09-SP1-3/auxx/samples/lib.defs
export TSMC_DLIB=/home/dkits/tsmc_65/TSMCHOME/digital/Back_End/cdk/tcbn65gplus_200a/tcbn65gplus
