# FILE_NAME = run_magic.tcl
# DESIGN_FILE = vco_aux_inv.mag
# all:
# 	magic -dnull -noconsole $(FILE_NAME) $(DESIGN_FILE)
# clean:
# 	rm -f *.spice *.ext


FILE_NAME = run_magic.tcl

all:
	magic -dnull -noconsole $(FILE_NAME)

clean:
	rm -f *.spice *.ext
